name: IPTV
description: IPTV Viewer

publish_to: "none"

version: 1.0.0+1
environment:
  sdk:
  flutter:

dependencies:
  flutter:
    sdk: flutter
  animations:
  cupertino_icons:
  dio:
  dio_cookie_manager:
  dio_http2_adapter:
  dio_flutter_transformer:
  freezed_annotation:
  logger:
  meta:
  intl:
  connectivity:
  characters:
  flutter_staggered_animations:
  json_annotation:
  archive:
  video_player:
  # video_player_web:
  video_player_web_hls:
    git:
      url: https://github.com/Mravuri96/video_player_web_hls.git
      ref: db71be8623ff29d6f5ca991fb0e98b125fb75533
  get:
  flutter_hooks:
  hooks_riverpod:
  dartx:
  url_launcher:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_runner:
  build_web_compilers:
  freezed:
  quiver:
  hive_generator:
  retrofit_generator:
  json_serializable:
  pedantic:
  effective_dart:
  firebase_core: "^0.5.0+1"
  firebase_analytics: "^6.0.2"

flutter:
  uses-material-design: true
  assets:
    - assets/streams.zip
    - assets/channels.zip
    
scripts:
  build: flutter pub run build_runner build --release --delete-conflicting-outputs
  watch: flutter pub run build_runner build --watch --delete-conflicting-outputs